// NOTE: Fabric publishing failed due to region limitation (Qatar region).
let
    Source = AzureStorage.DataLake(
        "https://goodreadsreviews60104310.dfs.core.windows.net/lakehouse/gold/curated_reviews/",
        [HierarchicalNavigation=true]
    ),
    DeltaTable = DeltaLake.Table(Source),
  #"Changed column type" = Table.TransformColumnTypes(DeltaTable, {{"review_id", type text}}),
  #"Removed blank rows" = Table.SelectRows(#"Changed column type", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
  #"Removed blank rows 1" = Table.SelectRows(#"Removed blank rows", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
  #"Removed blank rows 2" = Table.SelectRows(#"Removed blank rows 1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
  #"Added custom" = Table.AddColumn(#"Removed blank rows 2", "review_length", each Text.Length([review_text])),
  #"Filtered rows" = Table.SelectRows(#"Added custom", each [review_length] > 10),
  #"Filtered rows 1" = Table.SelectRows(#"Filtered rows", each [review_length] > 10),
  #"Removed columns" = Table.RemoveColumns(#"Filtered rows 1", {"review_length"}),
  #"Removed duplicates" = Table.Distinct(#"Removed columns", {"review_id"}),
  #"Trimmed text" = Table.TransformColumns(#"Removed duplicates", {{"name", each Text.Trim(_), type nullable text}}),
  #"Cleaned text" = Table.TransformColumns(#"Trimmed text", {{"name", each Text.Clean(_), type nullable text}}),
  #"Trimmed text 1" = Table.TransformColumns(#"Cleaned text", {{"title", each Text.Trim(_), type nullable text}}),
  #"Cleaned text 1" = Table.TransformColumns(#"Trimmed text 1", {{"title", each Text.Clean(_), type nullable text}}),
  #"Capitalized each word" = Table.TransformColumns(#"Cleaned text 1", {{"title", each Text.Proper(_), type nullable text}}),
  #"Capitalized each word 1" = Table.TransformColumns(#"Capitalized each word", {{"name", each Text.Proper(_), type nullable text}}),
  #"Grouped rows 2" = Table.Group(#"Capitalized each word 1", {"name"}, {{"avg_rating_per_author", each List.Average([rating]), type nullable number}})
in
Table.Group(#"Capitalized each word 1", {"name"}, {{"avg_rating_per_author", each List.Average([rating]), type nullable number}})
Table.Group(#"Added custom 1", {"book_id"}, {{"avg_word_count", each List.Average([word_count]), type any}})
    #"Grouped rows 2"